env: overcooked

env_args:
  worker: null  # Will need to be loaded with a pre-trained worker
  layout_name: "counter_circuit_o_1order"  # Default layout
  time_limit: 400
  shape_rewards: false
  stack_frames: false
  full_init: true
  args:
    horizon: 400
    layout_names: ["counter_circuit_o_1order"]
    encoding_fn: "OAI_egocentric"
    num_stack: 1
    device: "cpu"

test_greedy: True
test_nepisode: 32
test_interval: 10000
log_interval: 10000
runner_log_interval: 10000
learner_log_interval: 10000
t_max: 2050000