env: overcooked
map_name: cramped_room
runner: "episode" # Runs 1 env for an episode

env_args:
  layout_name: cramped_room
  worker_a_path: null  # Will use default from env_fn if null
  worker_b_path: null  # Will use default from env_fn if null
  horizon: 400
  deterministic: false
  stack_frames: false
  enc_fn: OAI_egocentric
  num_enc_channels: 27
  unknown_subtask_penalty: 0