env: overcooked
map_name: cramped_room  # Add this line to provide the map_name parameter

env_args:
  layout_name: cramped_room  # This is the actual parameter used by your env
  worker_a_path: null
  worker_b_path: null
  horizon: 400
  deterministic: false
  stack_frames: false
  enc_fn: OAI_egocentric
  num_enc_channels: 27